import { NextResponse } from "next/server"

// Transparent demo endpoint.
// This route does NOT call a real production music model. It returns a
// deterministic mock "track" so the landing page generator UI has something
// honest to show without claiming a live official model is connected.
export async function POST(req: Request) {
  let body: { prompt?: string; style?: string; mode?: "vocal" | "instrumental" }

  try {
    body = await req.json()
  } catch {
    return NextResponse.json({ error: "Invalid request body." }, { status: 400 })
  }

  const prompt = (body.prompt || "").trim()
  const style = body.style || "Pop"
  const mode: "vocal" | "instrumental" = body.mode === "instrumental" ? "instrumental" : "vocal"

  if (!prompt) {
    return NextResponse.json({ error: "A prompt or lyric idea is required." }, { status: 400 })
  }

  // Simulate generation latency.
  await new Promise((resolve) => setTimeout(resolve, 1400))

  const words = prompt.split(/\s+/).filter(Boolean)
  const titleSource = words.slice(0, 4).join(" ") || "Untitled Idea"
  const title = titleSource
    .replace(/[^\w\s-]/g, "")
    .split(" ")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ")

  const seed = Math.max(1, prompt.length)
  const durationSeconds = 120 + (seed % 90)
  const minutes = Math.floor(durationSeconds / 60)
  const seconds = String(durationSeconds % 60).padStart(2, "0")

  const bars = Array.from({ length: 32 }, (_, i) => {
    const wave = Math.sin((i + seed) * 0.6) * 30 + 40
    return Math.max(12, Math.min(100, Math.round(wave)))
  })

  return NextResponse.json({
    track: {
      title: title || "Untitled Idea",
      style,
      mode,
      duration: `${minutes}:${seconds}`,
      bars,
    },
    disclaimer:
      "Demo preview only. This response is generated by a mock API and is not produced by a live production music model.",
  })
}
